# JavaScript CircleCI 2.0 configuration file.
# Check https://circleci.com/docs/2.0/language-javascript/ for more details.
version: 2.1
jobs:
  node_v12:
    working_directory: "~/repo"
    docker:
      - image: "node:12.13"
    steps:
      - "checkout"
      - restore_cache:
          key: "node-v12.13-node-modules-{{ checksum \"package.json\" }}"
      - run:
          name: "Install packages"
          command: "npm ci"
      - save_cache:
          key: "node-v12.13-node-modules-{{ checksum \"package.json\" }}"
          paths:
            - "node_modules"
      - run:
          name: "Execute linters"
          command: "npm run lint"
      - run:
          name: "Execute tests"
          command: "npm test && npm run coverage"
      - run:
          name: "Build"
          command: "npm run build"
  node_v10:
    working_directory: "~/repo"
    docker:
      - image: "node:10.15"
    steps:
      - "checkout"
      - restore_cache:
          key: "node-v10.15-node-modules-{{ checksum \"package.json\" }}"
      - run:
          name: "Install packages"
          command: "npm ci"
      - save_cache:
          key: "node-v10.15-node-modules-{{ checksum \"package.json\" }}"
          paths:
            - "node_modules"
      - run:
          name: "Execute linters"
          command: "npm run lint"
      - run:
          name: "Execute tests"
          command: "npm test"
      - run:
          name: "Build"
          command: "npm run build"
workflows:
  version: 2
  build:
    jobs:
      - "node_v12"
      - "node_v10"
