name: "Build and test"
on:
  push:
    branches: ["master"]
  pull_request: {}
jobs:

  parameters:
    name: "Set parameters"
    runs-on: "ubuntu-latest"
    outputs:
      GITHUB_SHA: "${{ steps.GITHUB_SHA.outputs.GITHUB_SHA }}"
    steps:
      - id: "GITHUB_SHA"
        run: "echo \"::set-output name=GITHUB_SHA::$GITHUB_SHA\""

  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    needs: "parameters"
    strategy:
      matrix:
        node: ["10.15", "12.13"]
    steps:
      - uses: "actions/checkout@v2"
      - name: "Use Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: "${{ matrix.node }}"
      - name: "Cache dependencies"
        id: "node-modules-dependencies"
        uses: "actions/cache@v2"
        with:
          path: "./node_modules"
          key: "node-modules-${{ needs.parameters.outputs.GITHUB_SHA }}-${{ matrix.node }}"
      - name: "Install dependencies if needed"
        if: "steps.node-modules-dependencies.outputs.cache-hit != 'true'"
        run: "npm ci"

  test:
    name: "Test"
    needs: ["parameters", "build"]
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: ["10.15", "12.13"]
    steps:
      - uses: "actions/checkout@v2"
      - name: "Use Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: "${{ matrix.node }}"
      - name: "Restore cached dependencies"
        id: "node-modules-dependencies"
        uses: "actions/cache@v2"
        with: ,
          path: "./node_modules"
          key: "node-modules-${{ needs.parameters.outputs.GITHUB_SHA }}-${{ matrix.node }}"
      - name: "Execute tests"
        run: "npm test"
      - name: "Build test"
        run: "npm run build"

  lint:
    name: "Lint"
    needs: ["parameters", "build"]
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: ["10.15", "12.13"]
    steps:
      - uses: "actions/checkout@v2"
      - name: "Use Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: "${{ matrix.node }}"
      - name: "Restore cached dependencies"
        id: "node-modules-dependencies"
        uses: "actions/cache@v2"
        with:
          path: "./node_modules"
          key: "node-modules-${{ needs.parameters.outputs.GITHUB_SHA }}-${{ matrix.node }}"
      - name: "Execute linters"
        run: "npm run lint"
